// Shared Tailwind CSS Configuration for MCA Ace
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Light Theme Colors (Academic Excellence System 1)
        "surface-subtle": "#F8FAFC",
        "on-secondary-fixed": "#140067",
        "surface-tint": "#4d5d8b",
        "on-primary-fixed": "#051944",
        "surface-container-high": "#e3e9ed",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6d5fee",
        "border-light": "#E2E8F0",
        "on-primary": "#ffffff",
        "error": "#EF4444",
        "primary": "#021541",
        "pending": "#F59E0B",
        "surface-dim": "#d5dbdf",
        "surface": "#f5fafe",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#360f00",
        "surface-container": "#e9eff3",
        "tertiary-fixed": "#ffdbcd",
        "tertiary": "#310c00",
        "inverse-surface": "#2b3134",
        "inverse-primary": "#b5c5f9",
        "inverse-on-surface": "#ecf1f5",
        "on-tertiary-fixed-variant": "#7e2c00",
        "on-secondary-fixed-variant": "#3d28be",
        "on-error": "#ffffff",
        "surface-bright": "#f5fafe",
        "tertiary-fixed-dim": "#ffb597",
        "surface-container-low": "#eff4f8",
        "background": "#f5fafe",
        "secondary": "#5344d3",
        "surface-container-highest": "#dee3e7",
        "on-error-container": "#93000a",
        "on-background": "#161c1f",
        "on-secondary-container": "#fffbff",
        "outline": "#757680",
        "primary-container": "#1a2b56",
        "surface-variant": "#dee3e7",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#531b00",
        "outline-variant": "#c5c6d0",
        "secondary-fixed-dim": "#c5c0ff",
        "primary-fixed-dim": "#b5c5f9",
        "primary-fixed": "#dae1ff",
        "on-primary-fixed-variant": "#354572",
        "secondary-fixed": "#e4dfff",
        "success": "#10B981",
        "on-tertiary-container": "#fb6514",
        "on-surface": "#161c1f",
        "on-secondary": "#ffffff",
        "on-primary-container": "#8393c5",
        "on-surface-variant": "#45464f",
        
        // Dark Theme Colors override (Academic Excellence System 2)
        // Stored under dark-specific namespaces where naming overlaps
        dark: {
          "background": "#0d1322",
          "surface": "#0d1322",
          "surface-container-lowest": "#080e1d",
          "surface-container-low": "#151b2b",
          "surface-container": "#191f2f",
          "surface-container-high": "#242a3a",
          "surface-container-highest": "#2f3445",
          "on-surface": "#dde2f8",
          "on-surface-variant": "#c5c5d3",
          "primary": "#b5c4ff",
          "on-primary": "#00287c",
          "primary-container": "#2e4a9e",
          "on-primary-container": "#afc0ff",
          "secondary": "#ffb59a",
          "on-secondary": "#5b1b00",
          "secondary-container": "#cd4802",
          "outline": "#8e909d",
          "outline-variant": "#444651"
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "JetBrains Mono", "monospace"],
        "title-lg": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "title-lg": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}]
      }
    },
  },
}
